/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchAnimeRouteImport } from './routes/search.anime'
import { Route as AnimeAnimeIdSlugRouteImport } from './routes/anime.$animeId.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchAnimeRoute = SearchAnimeRouteImport.update({
  id: '/search/anime',
  path: '/search/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdSlugRoute = AnimeAnimeIdSlugRouteImport.update({
  id: '/anime/$animeId/$slug',
  path: '/anime/$animeId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search/anime': typeof SearchAnimeRoute
  '/anime/$animeId/$slug': typeof AnimeAnimeIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search/anime': typeof SearchAnimeRoute
  '/anime/$animeId/$slug': typeof AnimeAnimeIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search/anime': typeof SearchAnimeRoute
  '/anime/$animeId/$slug': typeof AnimeAnimeIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search/anime' | '/anime/$animeId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search/anime' | '/anime/$animeId/$slug'
  id: '__root__' | '/' | '/search/anime' | '/anime/$animeId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchAnimeRoute: typeof SearchAnimeRoute
  AnimeAnimeIdSlugRoute: typeof AnimeAnimeIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/anime': {
      id: '/search/anime'
      path: '/search/anime'
      fullPath: '/search/anime'
      preLoaderRoute: typeof SearchAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/$slug': {
      id: '/anime/$animeId/$slug'
      path: '/anime/$animeId/$slug'
      fullPath: '/anime/$animeId/$slug'
      preLoaderRoute: typeof AnimeAnimeIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchAnimeRoute: SearchAnimeRoute,
  AnimeAnimeIdSlugRoute: AnimeAnimeIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
