/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchAnimeRouteImport } from './routes/search.anime'
import { Route as AnimeAnimeIdSlugRouteImport } from './routes/anime.$animeId.$slug'
import { Route as AnimeAnimeIdSlugEpisodeEpisodeNumberRouteImport } from './routes/anime.$animeId.$slug.episode.$episodeNumber'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchAnimeRoute = SearchAnimeRouteImport.update({
  id: '/search/anime',
  path: '/search/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdSlugRoute = AnimeAnimeIdSlugRouteImport.update({
  id: '/anime/$animeId/$slug',
  path: '/anime/$animeId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdSlugEpisodeEpisodeNumberRoute =
  AnimeAnimeIdSlugEpisodeEpisodeNumberRouteImport.update({
    id: '/episode/$episodeNumber',
    path: '/episode/$episodeNumber',
    getParentRoute: () => AnimeAnimeIdSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/home': typeof HomeRoute
  '/search/anime': typeof SearchAnimeRoute
  '/anime/$animeId/$slug': typeof AnimeAnimeIdSlugRouteWithChildren
  '/anime/$animeId/$slug/episode/$episodeNumber': typeof AnimeAnimeIdSlugEpisodeEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/home': typeof HomeRoute
  '/search/anime': typeof SearchAnimeRoute
  '/anime/$animeId/$slug': typeof AnimeAnimeIdSlugRouteWithChildren
  '/anime/$animeId/$slug/episode/$episodeNumber': typeof AnimeAnimeIdSlugEpisodeEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/home': typeof HomeRoute
  '/search/anime': typeof SearchAnimeRoute
  '/anime/$animeId/$slug': typeof AnimeAnimeIdSlugRouteWithChildren
  '/anime/$animeId/$slug/episode/$episodeNumber': typeof AnimeAnimeIdSlugEpisodeEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/home'
    | '/search/anime'
    | '/anime/$animeId/$slug'
    | '/anime/$animeId/$slug/episode/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/home'
    | '/search/anime'
    | '/anime/$animeId/$slug'
    | '/anime/$animeId/$slug/episode/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/home'
    | '/search/anime'
    | '/anime/$animeId/$slug'
    | '/anime/$animeId/$slug/episode/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  HomeRoute: typeof HomeRoute
  SearchAnimeRoute: typeof SearchAnimeRoute
  AnimeAnimeIdSlugRoute: typeof AnimeAnimeIdSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/anime': {
      id: '/search/anime'
      path: '/search/anime'
      fullPath: '/search/anime'
      preLoaderRoute: typeof SearchAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/$slug': {
      id: '/anime/$animeId/$slug'
      path: '/anime/$animeId/$slug'
      fullPath: '/anime/$animeId/$slug'
      preLoaderRoute: typeof AnimeAnimeIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/$slug/episode/$episodeNumber': {
      id: '/anime/$animeId/$slug/episode/$episodeNumber'
      path: '/episode/$episodeNumber'
      fullPath: '/anime/$animeId/$slug/episode/$episodeNumber'
      preLoaderRoute: typeof AnimeAnimeIdSlugEpisodeEpisodeNumberRouteImport
      parentRoute: typeof AnimeAnimeIdSlugRoute
    }
  }
}

interface AnimeAnimeIdSlugRouteChildren {
  AnimeAnimeIdSlugEpisodeEpisodeNumberRoute: typeof AnimeAnimeIdSlugEpisodeEpisodeNumberRoute
}

const AnimeAnimeIdSlugRouteChildren: AnimeAnimeIdSlugRouteChildren = {
  AnimeAnimeIdSlugEpisodeEpisodeNumberRoute:
    AnimeAnimeIdSlugEpisodeEpisodeNumberRoute,
}

const AnimeAnimeIdSlugRouteWithChildren =
  AnimeAnimeIdSlugRoute._addFileChildren(AnimeAnimeIdSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  HomeRoute: HomeRoute,
  SearchAnimeRoute: SearchAnimeRoute,
  AnimeAnimeIdSlugRoute: AnimeAnimeIdSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
